export const T = {
  en: {
    title: "MANDALART",
    tagline: "ONE GOAL. EIGHT PATHS. SIXTY-FOUR STEPS.",
    loading: "Loading…",
    menu: { profile: "Profile", create: "New Mandalart", manage: "Manage", about: "What is Mandalart?" },
    back: "Back",
    replay: "Replay guide",
    categories: "Suggested categories",
    categoriesHint: "Tap one to drop it into an open slot",
    fullView: "Full grid",
    compactView: "Focus view",
    catList: [
      { k: "Health", d: "Sleep, fitness, nutrition" },
      { k: "Career", d: "Skills, role, milestones" },
      { k: "Finance", d: "Savings, income, habits" },
      { k: "Relationships", d: "Family, friends, community" },
      { k: "Growth", d: "Learning, mindset, reflection" },
      { k: "Hobby", d: "Creative outlets, play" },
      { k: "Mindset", d: "Discipline, calm, focus" },
      { k: "Travel", d: "Places, experiences" },
      { k: "Education", d: "Study, courses, knowledge" },
      { k: "Creativity", d: "Art, writing, music, design" },
      { k: "Spirituality", d: "Values, purpose, gratitude" },
      { k: "Social", d: "Networking, community impact" },
      { k: "Productivity", d: "Systems, tools, time management" },
      { k: "Leadership", d: "Influence, communication, vision" },
      { k: "Language", d: "Speaking, reading, listening" },
      { k: "Fitness", d: "Strength, flexibility, endurance" },
      { k: "Food", d: "Cooking, diet, meal habits" },
      { k: "Environment", d: "Space, organization, sustainability" },
      { k: "Rest", d: "Sleep, recovery, digital detox" },
      { k: "Passion Project", d: "Side venture, big idea, dream goal" },
    ],
    grid: {
      untitled: "Untitled Mandalart",
      mainGoal: "Main goal",
      subGoal: "Sub-goal",
      detail: "Detail",
      saving: "Saving…",
      savedJustNow: "Saved just now",
      savedAgo: (s) => `Saved ${s}s ago`,
      unsaved: "Unsaved changes",
      save: "Save",
      descTitle: "Add a short note",
      descViewTitle: "Note",
      descPlaceholder: "What does this step actually involve?",
      descSave: "Save",
      descCancel: "Cancel",
      descClose: "Close",
      visPrivate: "Private",
      visPublic: "Public",
      visHintPrivate: "Only you can see this.",
      visHintPublic: "Friends can view this (no editing).",
    },
    manage: {
      title: "Your Mandalarts",
      empty: "Nothing here yet — create your first one.",
      open: "Open",
      create: "+ New mandalart",
      delete: "Delete",
      deleteConfirm: "Delete this mandalart? This cannot be undone.",
      deleteYes: "Yes, delete",
      deleteNo: "Cancel",
    },
    auth: {
      email: "Email",
      password: "Password",
      username: "Display name",
      signIn: "Sign in",
      signUp: "Create account",
      toSignUp: "New here? Create an account",
      toSignIn: "Already have an account? Sign in",
      signOut: "Sign out",
      signOutConfirm: "Are you sure you want to sign out?",
      signOutYes: "Sign out",
      signOutNo: "Cancel",
      termsPrefix: "I agree to the",
      termsLink: "Terms of Use",
      termsRequired: "Please accept the Terms of Use to continue.",
      termsTitle: "Terms of Use",
      termsClauses: [
        "Your goal data is stored securely on Supabase servers. We do not sell or share your data with third parties.",
        "Your mandalarts are private by default. You control what is shared with friends.",
        "You may delete your account and all associated data at any time by contacting support.",
        "Do not use this service for any unlawful, harmful, or abusive purposes.",
        "This app is provided as-is. We are not liable for any loss of data or unintended use.",
      ],
    },
    friends: {
      yourCode: "Your friend code",
      copy: "Copy",
      copied: "Copied",
      addTitle: "Add a friend",
      placeholder: "Name#0000",
      add: "Add",
      exactHint: "Enter their exact code — there's no name search, just like a Battle Tag.",
      errSelf: "That's your own code.",
      errNotFound: "No one found with that code.",
      errAlready: "You're already connected with this code.",
      sent: (code) => `Friend request sent to ${code}.`,
      requests: "Friend requests",
      accept: "Accept",
      decline: "Decline",
      list: "Friends",
      empty: "No friends yet — add one above.",
      statusAccepted: "Friends",
      statusPending: "Pending",
      viewMandalarts: "View mandalarts",
      viewerListTitle: (code) => `${code}'s public mandalarts`,
      viewerEmpty: "This friend hasn't made anything public yet.",
      viewerOpen: "Open",
      viewerBadge: "Public · view only",
    },
    onboarding: [
      { t: "What is a Mandalart?", b: "A 9×9 grid built around one goal. Each of its 8 neighbors becomes the seed of its own surrounding grid." },
      { t: "The center converges", b: "The 8 cells around your main goal mirror the centers of the 8 outer blocks — edit either side and both update." },
      { t: "Write as if it's done", b: "Phrase entries in the present tense, as already achieved. It changes how you act toward them." },
      { t: "Make it yours", b: "Switch themes, toggle dark mode, play music while you write, and tag related cells to jump between them." },
      { t: "Ready", b: "Open a blank grid and place your first goal in the center." },
    ],
    about: {
      title: "What is Mandalart?",
      body: [
        "A Mandalart is a 9×9 grid goal-setting technique built around one central goal, broken into 8 sub-goals, each of which is further broken into 8 concrete action items. It originated in Japan in the 1980s and became widely known after baseball player Shohei Ohtani's own Mandalart from his high school years was publicized.",
        "This app's grid follows one rule: the 8 cells around your main goal are directly linked to the center cell of each of the 8 outer blocks — edit one and the other updates too. Eight separate paths, converging on one goal.",
        "Write entries in the present tense, as if already achieved, rather than as something you intend to do. It changes how you act toward them.",
      ],
      tipsTitle: "Quick tips",
      tips: [
        "Start with your main goal in the center. Make it specific and personal.",
        "Fill in the 8 surrounding sub-goals before touching any outer block.",
        "Use the suggested categories as a starting point, not a constraint.",
        "Link related cells with the ⛓ icon to jump between them instantly.",
        "Set your mandalart to Public so trusted friends can see your progress.",
        "Play background music to enter a focused, distraction-free writing state.",
      ],
      ohtaniLabel: "The Ohtani method",
      ohtani: "Shohei Ohtani created his Mandalart at age 16 with the goal of becoming a pro baseball player. His 8 sub-goals included nutrition, mental strength, speed, and pitching power — each broken into 8 daily habits. He achieved every one of them.",
    },
    music: { off: "Off", loopNote: "Loops until stopped" },
    next: "Next", prev: "Back", start: "Start writing", skip: "Skip",
    sound: "Sound", lang: "Language", theme: "Theme", dark: "Dark", light: "Light",
  },
  ko: {
    title: "만다라트",
    tagline: "하나의 목표. 여덜 갈래. 예순네 걸음.",
    loading: "불러오는 중…",
    menu: { profile: "프로필", create: "새 만다라트", manage: "만다라트 관리", about: "만다라트란?" },
    back: "뒤로",
    replay: "가이드 다시 보기",
    categories: "추천 카테고리",
    categoriesHint: "탭하면 빈 칸에 채워져요",
    fullView: "전체 보기",
    compactView: "포커스 보기",
    catList: [
      { k: "건강", d: "수면, 운동, 영양" },
      { k: "커리어", d: "역량, 직무, 마일스톤" },
      { k: "재정", d: "저축, 수입, 습관" },
      { k: "관계", d: "가족, 친구, 공동체" },
      { k: "성장", d: "학습, 마인드셋, 회고" },
      { k: "취미", d: "창작, 여가" },
      { k: "마인드셋", d: "규율, 평정심, 집중" },
      { k: "여행", d: "장소, 경험" },
      { k: "교육", d: "공부, 강의, 지식" },
      { k: "창의성", d: "미술, 글쓰기, 음악, 디자인" },
      { k: "영성", d: "가치관, 목적, 감사" },
      { k: "소셜", d: "네트워킹, 커뮤니티 참여" },
      { k: "생산성", d: "시스템, 도구, 시간 관리" },
      { k: "리더십", d: "영향력, 소통, 비전" },
      { k: "언어", d: "말하기, 읽기, 듣기" },
      { k: "체력", d: "근력, 유연성, 지구력" },
      { k: "식습관", d: "요리, 식단, 식사 습관" },
      { k: "환경", d: "공간, 정리, 지속가능성" },
      { k: "회복", d: "수면, 휴식, 디지털 디톡스" },
      { k: "사이드 프로젝트", d: "부업, 큰 아이디어, 꿈의 목표" },
    ],
    grid: {
      untitled: "제목 없는 만다라트",
      mainGoal: "메인 목표",
      subGoal: "하위 목표",
      detail: "세부 항목",
      saving: "저장 중…",
      savedJustNow: "방금 저장됨",
      savedAgo: (s) => `${s}초 전 저장됨`,
      unsaved: "저장되지 않은 변경사항",
      save: "저장",
      descTitle: "짧은 설명 추가",
      descViewTitle: "메모",
      descPlaceholder: "이 단계가 구체적으로 어떤 걸 의미하나요?",
      descSave: "저장",
      descCancel: "취소",
      descClose: "닫기",
      visPrivate: "비공개",
      visPublic: "공개",
      visHintPrivate: "나만 볼 수 있어요.",
      visHintPublic: "친구들이 볼 수 있어요 (수정은 불가).",
    },
    manage: {
      title: "내 만다라트",
      empty: "아직 없어요 — 첫 만다라트를 만들어보세요.",
      open: "열기",
      create: "+ 새 만다라트",
      delete: "삭제",
      deleteConfirm: "이 만다라트를 삭제할까요? 되돌릴 수 없어요.",
      deleteYes: "삭제",
      deleteNo: "취소",
    },
    auth: {
      email: "이메일",
      password: "비밀번호",
      username: "표시 이름",
      signIn: "로그인",
      signUp: "계정 만들기",
      toSignUp: "처음이신가요? 계정 만들기",
      toSignIn: "이미 계정이 있으신가요? 로그인",
      signOut: "로그아웃",
      signOutConfirm: "정말 로그아웃 하시겠어요?",
      signOutYes: "로그아웃",
      signOutNo: "취소",
      termsPrefix: "다음에 동의합니다:",
      termsLink: "이용약관",
      termsRequired: "계속하려면 이용약관에 동의해주세요.",
      termsTitle: "이용약관",
      termsClauses: [
        "작성하신 목표 데이터는 Supabase 서버에 안전하게 저장되며, 제3자에게 제공되거나 판매되지 않습니다.",
        "만다라트는 기본적으로 비공개입니다. 공유 여부는 직접 설정할 수 있습니다.",
        "언제든지 고객 지원을 통해 계정 및 모든 데이터를 삭제 요청할 수 있습니다.",
        "서비스를 불법적이거나 유해한 목적으로 사용하지 않습니다.",
        "이 앱은 현 상태로 제공되며, 데이터 손실이나 의도치 않은 사용으로 인한 책임을 지지 않습니다.",
      ],
    },
    friends: {
      yourCode: "내 친구 코드",
      copy: "복사",
      copied: "복사됨",
      addTitle: "친구 추가",
      placeholder: "이름#0000",
      add: "추가",
      exactHint: "정확한 코드를 입력하세요 — 이름 검색은 없어요, 배틀태그처럼요.",
      errSelf: "본인 코드예요.",
      errNotFound: "해당 코드를 가진 사용자가 없어요.",
      errAlready: "이미 연결된 코드예요.",
      sent: (code) => `${code}님께 친구 요청을 보냈어요.`,
      requests: "받은 친구 요청",
      accept: "수락",
      decline: "거절",
      list: "친구 목록",
      empty: "아직 친구가 없어요 — 위에서 추가해보세요.",
      statusAccepted: "친구",
      statusPending: "대기 중",
      viewMandalarts: "만다라트 보기",
      viewerListTitle: (code) => `${code}님의 공개 만다라트`,
      viewerEmpty: "아직 공개로 설정한 만다라트가 없어요.",
      viewerOpen: "열기",
      viewerBadge: "공개 · 보기 전용",
    },
    onboarding: [
      { t: "만다라트란?", b: "하나의 목표를 중심으로 한 9×9 그리드예요. 둘레의 8칸은 각자 또 하나의 그리드를 거느리는 씨앗이 됩니다." },
      { t: "중심으로 수렴해요", b: "메인 목표 둘레 8칸은 바깥 8개 블록의 중심 칸과 짝을 이뤄요. 한쪽을 고치면 양쪽 다 바뀝니다." },
      { t: "이미 이룬 것처럼 쓰기", b: "현재형, 이미 달성한 것처럼 적어보세요. 그렇게 적으면 행동도 그렇게 따라갑니다." },
      { t: "내 스타일로", b: "테마와 다크모드를 바꾸고, 음악을 들으며 작성하고, 연결된 칸을 태그해서 바로 이동해보세요." },
      { t: "준비됐어요", b: "빈 그리드를 열고 중앙에 첫 목표를 적어보세요." },
    ],
    about: {
      title: "만다라트란?",
      body: [
        "만다라트는 하나의 핵심 목표를 중심에 두고, 그것을 이루기 위한 8개의 하위 목표, 그리고 각 하위 목표를 다시 8개의 구체적인 실행 항목으로 쪼개는 9×9 격자 형태의 목표 설정 기법이에요. 1980년대 일본에서 만들어졌고, 야구선수 오타니 쇼헤이가 고교 시절 작성한 만다라트가 알려지면서 널리 퍼졌어요.",
        "이 앱의 그리드는 한 가지 원칙을 따라요 — 메인 목표 둘레의 8칸은 바깥에 있는 8개 블록 각각의 중심 칸과 그대로 연결돼 있어서, 한쪽을 고치면 다른 쪽도 같이 바뀌어요. 여덟 갈래로 흩어진 하위 목표들이 결국 하나의 중심으로 수렴한다는 뜻이에요.",
        "작성할 때는 '할 것이다' 대신 '이미 이뤘다'는 현재형으로 적어보세요. 그렇게 적힌 문장은 실제 행동에도 다르게 작용해요.",
      ],
      tipsTitle: "빠른 팁",
      tips: [
        "중앙에 메인 목표부터 적어보세요. 구체적이고 내 것이어야 해요.",
        "바깥 블록을 채우기 전에, 메인 목표 주변 8칸(하위 목표)부터 완성하세요.",
        "추천 카테고리는 출발점이지, 제약이 아니에요. 자유롭게 수정하세요.",
        "⛓ 아이콘으로 연관된 칸을 연결하면 한 번에 이동할 수 있어요.",
        "완성한 만다라트를 공개로 설정하면, 친구들과 목표를 나눌 수 있어요.",
        "배경 음악을 틀면 집중력 있는 글쓰기 상태에 더 쉽게 들어갈 수 있어요.",
      ],
      ohtaniLabel: "오타니 방식",
      ohtani: "오타니 쇼헤이는 16살에 '프로야구 선수가 되겠다'는 목표로 만다라트를 작성했어요. 영양, 멘탈, 스피드, 구위 등 8개의 하위 목표, 각각을 위한 64가지 일상 습관을 세웠고 — 모두 실현했습니다.",
    },
    music: { off: "끄기", loopNote: "정지할 때까지 반복 재생" },
    next: "다음", prev: "이전", start: "작성 시작", skip: "건너뛰기",
    sound: "사운드", lang: "언어", theme: "테마", dark: "다크", light: "라이트",
  },
};
